// Pure DB → HuggingFace-dataset payload builder (no side effects, no network).
//
// Shared by the CLI (scripts/hf-sync.ts) and the serverless endpoint (api/hf-sync.ts) so the
// "guarantee no information loss" mapping lives in exactly ONE place. Given a full DB snapshot it
// emits the file set for each private dataset repo. Nothing is dropped: the snapshot repo carries
// every entity verbatim (including ops + audit ledger); the headline repos are convenience views.

// Entity collections that hold persisted records (mirrors store.ts ENTITY_KEYS + ledgers).
const ENTITY_KEYS = [
  'workspaces', 'notes', 'tasks', 'files', 'events',
  'phenomena', 'templates', 'pairs', 'sources', 'childes_docs', 'childes_anns',
]
const LEDGER_KEYS = ['ops', 'audit']

const jsonl = (rows) => (rows || []).map((r) => JSON.stringify(r)).join('\n') + ((rows && rows.length) ? '\n' : '')
const arr = (db, k) => (Array.isArray(db?.[k]) ? db[k] : [])

function readme(title, body) {
  return `---
license: other
tags: [xblimps, linguistics, minimal-pairs, multilingual]
pretty_name: ${JSON.stringify(title)}
---

# ${title}

${body}

> Private mirror generated by the xBLiMPs annotation platform's HuggingFace sync.
> This is an automated, zero-loss backup — do not hand-edit; re-run the sync to update.
`
}

// Build the dataset name → { files } map. `stamp` is an ISO timestamp passed in (callers stamp,
// so this stays pure). `org` defaults to the xBLiMPs org.
export function buildArtifacts(db, { stamp, org = 'xBLiMPs' } = {}) {
  const ts = stamp || ''
  const counts = {}
  for (const k of [...ENTITY_KEYS, ...LEDGER_KEYS]) counts[k] = arr(db, k).length

  // Flatten templates/pairs with a couple of denormalised convenience columns for HF viewers.
  const templates = arr(db, 'templates').map((t) => ({ ...t }))
  const pairs = arr(db, 'pairs').map((p) => ({ ...p }))

  // Full-fidelity snapshot repo: every entity + ledgers, plus a single combined JSON.
  const snapshotFiles = {
    'snapshot.json': JSON.stringify({ generated_at: ts, counts, db }, null, 2),
    'README.md': readme('xBLiMPs — full platform snapshot', [
      `Complete, zero-loss mirror of the xBLiMPs annotation platform, generated **${ts}**.`,
      '',
      'Per-entity record counts:',
      '',
      ...[...ENTITY_KEYS, ...LEDGER_KEYS].map((k) => `- \`${k}\`: ${counts[k]}`),
      '',
      'Files: `snapshot.json` (combined) plus one `<entity>.jsonl` per collection.',
    ].join('\n')),
  }
  for (const k of [...ENTITY_KEYS, ...LEDGER_KEYS]) snapshotFiles[`${k}.jsonl`] = jsonl(arr(db, k))

  const artifacts = {
    [`${org}/xblimps-snapshot`]: { files: snapshotFiles },
    [`${org}/xblimps-templates`]: {
      files: {
        'templates.jsonl': jsonl(templates),
        'README.md': readme('xBLiMPs — templates', `All ${templates.length} authoring templates (slots, grammatical/ungrammatical patterns, fine-grained Minimalist analysis, citations, validation). Generated **${ts}**.`),
      },
    },
    [`${org}/xblimps-minimal-pairs`]: {
      files: {
        'minimal_pairs.jsonl': jsonl(pairs),
        'README.md': readme('xBLiMPs — minimal pairs', `All ${pairs.length} minimal pairs (good/bad sentences, contrast tokens, parses, CoNLL-U, gloss, feature bundle, perturbation). Generated **${ts}**.`),
      },
    },
  }
  return { artifacts, counts }
}

export { ENTITY_KEYS, LEDGER_KEYS }
